#!/bin/bash
# @copyright 2021 Network RADIUS SAS (legal@networkradius.com)
# Author: Jorge Pereira <jorge@freeradius.org>
##

if [ -z "$CI_TEST_USER" ]; then
	echo "$0: ERROR: Missing the env CI_TEST_USER"
	exit 1
fi

if [ -z "$CI_TEST_PASS" ]; then
	echo "$0: ERROR: Missing the env CI_TEST_PASS"
	exit 1
fi

# Setup the basic user setting
if [ -f /etc/redhat-release ]; then
	cat > /etc/pam.d/sshd <<EOF
# Generated by $0
#%PAM-1.0
auth     required   pam_sepermit.so
auth     required   pam_radius_auth.so conf=/etc/pam_radius_auth.conf debug retry=123 client_id=666
account  required   pam_nologin.so
account  include    password-auth
password include    password-auth
# pam_selinux.so close should be the first session rule
session  required   pam_selinux.so close
session  required   pam_loginuid.so
# pam_selinux.so open should only be followed by sessions to be executed in the user
#context
session  required   pam_selinux.so open env_params
session  required   pam_namespace.so
session  optional   pam_keyinit.so force revoke
session  include    password-auth
EOF
else
	cat > /etc/pam.d/sshd <<EOF
# Generated by $0
auth    sufficient      pam_radius_auth.so conf=/etc/pam_radius_auth.conf debug retry=123 client_id=666
account    required     pam_nologin.so
@include common-account
session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close
session    required     pam_loginuid.so
session    optional     pam_keyinit.so force revoke
@include common-session
session    optional     pam_motd.so  motd=/run/motd.dynamic
session    optional     pam_motd.so noupdate
session    optional     pam_mail.so standard noenv # [1]
session    required     pam_limits.so
session    required     pam_env.so # [1]
session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale
session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so open
@include common-password
EOF
fi

cat > /etc/pam_radius_auth.conf <<EOF
# Generated by $0
[::1]         testing123  5
127.0.0.1     testing123  5
EOF
