#! /bin/sh
# @copyright 2024 Network RADIUS SAS (legal@networkradius.com)
##

cat > /etc/rsyslog.conf <<'EOF'
# Generated by $0

module(load="imuxsock")

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$WorkDirectory /var/spool/rsyslog

auth,authpriv.*                 /var/log/auth.log
EOF

rm -f /var/log/auth.log
